language: node_js
node_js:
  - "node"

install:
- cd webapp
- npm install
script:
- ./node_modules/.bin/eslint .
- npm test -- --coverage
before_deploy:
- npm run build
- npm pack
deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "*.tgz"
  skip_cleanup: true
  on:
    tags: true
