language: node_js
node_js:
  - "node"

install:
- cd webapp
- npm install
script:
- ./node_modules/.bin/eslint .
- npm test -- --coverage
before_deploy:
- npm run build
- tar zcf webapp-build-$(git describe --tags).tar.gz build/
deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
