version: "2.2"
services:
  server:
    build:
      context: .
      args:
          http_proxy: "${http_proxy}"
          https_proxy: "${https_proxy}"
    hostname: server
    image: how-is-my-driving
    restart: on-failure
    ports:
      - "3030:3030"
  database:
    hostname: database
    image: mongo
    restart: on-failure
    volumes:
    - ./mongo-data-db:/data/db
