version: "2.2"
services:
  server:
    build:
      context: ./docker-build/
    entrypoint:
    - fdbk-server
    - --config-file
    - /app/config.json
    - --port
    - "8080"
    hostname: server
    image: fdbk
    restart: on-failure
    ports:
    - "8080:8080"
    volumes:
    - ./config/mongo.json:/app/config.json
  database:
    hostname: database
    image: mongo
    restart: on-failure
    volumes:
    - ./mongo-data-db:/data/db
